### ISSUE TITLE
approve limited amount of tokens

### ISSUE THREAD

**Issue by Kwaskoff** [syncswap/SyncSwap-Testnet-Issue-Tracker#10]
When I approved 1 USDC - your interface don't understand it, and ask approve USDC still. Works only when I approved unlimited amount of USDC
![image](https://user-images.githubusercontent.com/15308024/172570204-05b78334-f4b1-47ba-90db-e2cecbfbf868.png)
https://zksync2-testnet.zkscan.io/tx/0xb29bbdeab9bd2936b3f8a40c326b0262887b5bea19843963a2ba83d6a3b32a28/token-transfers

**Comment by syncswapxyz** [comment]
Thank you, we will investigate it

**Comment by 0xnakato** [comment]
Close as solved
