### ISSUE TITLE
correct the description or remove the fee

### ISSUE THREAD

**Issue by Kwaskoff** [syncswap/SyncSwap-Testnet-Issue-Tracker#11]
I need to pay the fee for unwrapping ![image](https://user-images.githubusercontent.com/15308024/172571552-1b9fbcff-0d4b-4f1b-ae56-c85568c25a55.png)
But your description guarantees me unwrapping without fee🙃
![image](https://user-images.githubusercontent.com/15308024/172571831-7d40361a-b4a9-4d7a-9a71-c79c8b46aa63.png)

**Comment by syncswapxyz** [comment]
It shows you have supplied 0 UST (on the `Your Supply` tab), it seems you used FRAX or DAI, etc., instead of UST to mint USDs, and it will charge a fee when you unwrap to UST, which is considered as a swap. Can you try to unwrap to assets you supplied (wrapped from) before?
