### ISSUE TITLE
feedback and suggestions

### ISSUE THREAD

**Issue by Al777fa** [syncswap/SyncSwap-Testnet-Issue-Tracker#4]
Hello, tested the platform, all went well
Liked it:
- Friendly interface, suitable for newcomers to the platform
- Quick execution of commands
-many languages.
I think we should add: 
-deposit and credit features
-Fill in the empty fields on the sides with an image (trademark or something else)
-% of my pools, balances, etc.
-how my cryptocurrency balance has changed in $ and %.
-article
-possibly a slogan for more appeal.
-There are a couple of proposals on the interface, namely in the header would be nice to add a tab MORE with links to the environment, documentation and a mini-tutorial on the project.
 Wallet I used:0xc7182e288De705F1c9a7dE8EE17b3890cA48F7Ce

**Comment by damnational** [comment]
Hello there, just tested the "staking" part.

It was smooth and had no issues. My suggestion is;

- After pressing the stake button, the page does not show the amount I have staked when the transaction is completed. I have to go back to see my stake amount. It would be better to see the amount on that page (see attachment)

my wallet: 0xcF24f9DB11D7cf69b1f6f438c1A5b576456F6df2

Have a nice day.

<img width="587" alt="Screen Shot 2022-05-04 at 12 04 46" src="https://user-images.githubusercontent.com/104895953/166654020-b0a8c021-2b5f-41b1-b7c8-f532696ae9eb.png">

**Comment by 0xnakato** [comment]
Close as solved.
